version: 2

models:
  - name: stg_glamira__summary
    columns:
      - name: collection
        tests:
          - not_null

  - name: stg_glamira__product
    columns:
      - name: product_id
        tests:
          - not_null

  - name: stg_glamira__ip2location
    columns:
      - name: ip_address
        tests:
          - not_null
