version: 2

sources:
  - name: glamira_raw
    database: "{{ env_var('BQ_PROJECT_ID', var('project_id')) }}"
    schema: "{{ env_var('BQ_DATASET_ID', var('raw_dataset')) }}"
    tables:
      - name: summary
      - name: product_info
      - name: ip2location
