version: 2

models:
  - name: int_stone_options
  
  - name: int_colour_options

  - name: int_checkout_events
    columns:
      - name: sale_id
        tests:
          - not_null
      - name: order_id
        tests:
          - not_null
      - name: product_id
        tests:
          - not_null
