name: "glamira_dbt"
version: "1.0.0"

profile: "glamira_dbt"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  project_id: "concise-voice-486808-m9"
  raw_dataset: "glamira_project"

models:
  glamira_dbt:
    staging:
      +schema: glamira_staging
      +materialized: view
      +tags: ["staging"]
    intermediate:
      +schema: glamira_intermediate
      +materialized: table
      +tags: ["intermediate"]
    mart:
      +schema: glamira_mart
      +materialized: table
      +tags: ["mart"]
